### ISSUE TITLE
Chinese localization

### ISSUE THREAD

**Issue by r888800009** [IgorTimofeev/OpenComputers#100]
Hello there.
I want to translate MineOS and most applications into Chinese and a small amount of English.
But I need to know how MineOS and most applications can do language localization, and some things to be aware of.
Thank you.

**Comment by IgorTimofeev** [comment]
Hello. It's a rather laborious process, are you sure that you need it? Anyway I will be happy with any pull requests :)

By the way, localization concept of is quite simple: there is main configuration file located at **/MineOS/System/Properties.cfg**, it contains a **language** field that is responsible for the current localization. This field is being created during OS installation process. As a result, any developer can call the  **MineOSCore.getCurrentApplicationLocalization()** or **MineOSCore.getLocalization(pathToLanguagesDirectory)** method. The first one will search for system language in **\<launched application.app\>/Resources/Localization/\<system language\>.lang** automatically and the second one will do the same in specified directory. If there is no such language, the first from file list will be selected. MineOS localizations are located at **/MineOS/System/Localizations/**. So that's it.

**Comment by r888800009** [comment]
I got some broken wide characters.
```
    properties = "屬性",
    type = "型類",
    size = "尺寸",
    date = "日期",
    path = "路徑",
```
In this case, the wide character "性" breaks after moving the window, "路徑" loses "徑".
![1](https://user-images.githubusercontent.com/14235139/36483457-1e39d0d0-1751-11e8-8238-badff0aedfb3.PNG)

In this case, the content menu width is not displayed correctly.
![default](https://user-images.githubusercontent.com/14235139/36483461-21f0e2c2-1751-11e8-955b-cd1474e1e491.PNG)

![2](https://user-images.githubusercontent.com/14235139/36484275-aeee51e4-1753-11e8-95a4-00d4705d650d.PNG)

I'm not sure if this is GUI or Double Buffer problem.Maybe you can fix it, or provide me with some relevant information.

If you need to test.


I use a fixed font.hex (future versions of OC will be fixed).
MightyPirates/OpenComputers#2710

There are also localization files
r888800009/OpenComputers@8846c1b

Thx

**Comment by IgorTimofeev** [comment]
No, I can't fix it without catastrophic performance losing. It happens because some of your symbols are "wide" in mod char rendering table. To fix this, I'll need to add tons of checks via unicode.isWide() in doubleBuffering library - so it will be "blaaah why so slow"

**Comment by r888800009** [comment]
I tested unicode.isWide () with unicode.wlen () and table.
This my computer configuration.
![default](https://user-images.githubusercontent.com/14235139/36499970-d1616868-177d-11e8-8e3b-c8bac3983018.PNG)

Using table is 1.2% of the other two time consuming.The first two are .isWide () and wlen (), the latter three are table.
This is test file.
r888800009/r809-MineOS-tools@0002776 
![test](https://user-images.githubusercontent.com/14235139/36499968-d10560f4-177d-11e8-87a1-3845eca537af.PNG)

This is desktop performance.
![default](https://user-images.githubusercontent.com/14235139/36499969-d135f192-177d-11e8-8527-a7cd6127a089.PNG)
I estimate that after adding wide characters, the performance loss of about 0.01s.
That is, in the desktop environment, os.clock () changes about will become 0.02s.

But in the case of a small table results.
Still not sure about the big table and the dynamically generated wide character length performance.

It might be possible to create a function "wideEnable (boolean)" to change the render callback function, which preserves the original performance and also has the ability to display wide-character flexibility.

**Comment by IgorTimofeev** [comment]
Main calculations must be in buffer.text() function instead of buffer.draw() because we need to shift buffer index in drawing stage and draw string correctly. So each text rendering operation will do it for each character in specified string.

Caching characters width in table is not an option because of increased memory consumption. Again: double buffering library aims to achieve maximum performance, minimum cost of computer resources, and not to consider some particular cases such as irregular width of some glyphs in some languages in OpenComputers mod.

In addition, in almost all text methods of GUI library (and software that uses localization files) we'll need to use the unicode.wlen() function, combining it with unicode.len() to achieve the result - to get the right width of the context menu from your screenshots, for example.

Anyway, the loss of even 0.01 seconds of os.clock() delta is an unacceptable luxury, I spent hours achieving those 0.01-0.05 seconds via code refactoring for improving OS performance. Are you sure that we must fix mod disadvantages like this from MineOS side (not mod side)?

**Comment by r888800009** [comment]
I tried to modify the buffer.Text () and use the special format of the localization file.
r888800009/OpenComputers@6985330  


If i want show **"選定的新文件夾"**,Wide-text localization files must be pre-encoded in this way.
```
newFolderFromChosen = "選\0定\0的\0新\0文\0件\0夾\0",
```
This will eliminate the need for cache tables.

I made 10000, 50000, 100000 loop calls to the original function and the modified function. The modified function is sometimes faster and sometimes slower. I do not know why.

Chinese pre-encoded files will not be too large, about 7kb.
However, some symbols in the background will still cause errors when rendering.
![test1](https://user-images.githubusercontent.com/14235139/36532571-fe6b102e-17fb-11e8-9e33-44867d8ba4d1.gif)

**Comment by IgorTimofeev** [comment]
So what do you want me to do from my side? I don't really care about localization file sizes on HDD if it doesn't affects OS performance, and I won't merge anything that can slow down existing performance - even with a cost of some poor milliseconds.

**Comment by r888800009** [comment]
If you do not mind, perhaps in the system localization file to add a `enableWideCharacters = true`
When switching the system language, it reminds users or downloads a wide version of DoubleBuffering and replaces it without affecting non-wide-character users.

Thank you for answering this issue patiently. :)

**Comment by IgorTimofeev** [comment]
It sounds like a big, big crutch. At system level I will not do anything like this: if you wish, you can upload a publication to App Market with the appropriate dependencies, adding Chinese localization and your version of double buffering library.

**Comment by r888800009** [comment]
Well, I will through the App Market.
Close issues until there is a better solution.

**Comment by IgorTimofeev** [comment]
Rendering part of this issue finally fixed in 
 https://github.com/IgorTimofeev/MineOS/commit/cdbb421e7ec739b44279f500665c45540a21a075. The wlen shit is cached, so overall performance shouldn't be affected very much. There's still problem with weird text wrapping in text library, but that's another case

THANKS FOR 5 YEARS WAITING
